### PR TITLE
[KOGITO-4888] Update Prometheus operator GitHub link

### PR DESCRIPTION
**Pull request by Kevin-Mok**
See: https://issues.redhat.com/browse/KOGITO-4888

Upstream PR: https://github.com/kiegroup/kogito-operator/pull/836

## Requirements
Many thanks for submiting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: 
- [x] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by spolti — APPROVED** [review]

**Comment by spolti** [comment]
@msmagnanijr can you please add the bot on this repo?

**Review by sutaakar — APPROVED** [review]

**Comment by Kevin-Mok** [comment]
For the BDD tests, it seems that the tests themselves passed, but archiving the JUnit-formatted test results failed.

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@sutaakar, the CI error is some infra problem?

**Comment by msmagnanijr** [comment]
> @msmagnanijr can you please add the bot on this repo?

Sure! i will do it today :)

**Comment by sutaakar** [comment]
@Kevin-Mok Can you update Kogito operator in go.mod? I have a suspicion that the test failures come from using old Kogito operator version.

**Comment by Kevin-Mok** [comment]
@sutaakar I'm running into this issue when trying to update to v1.4.0:
```
 github.com/kiegroup/kogito-operator@v1.4.0: parsing go.mod:                                                                                     
        module declares its path as: github.com/kiegroup/kogito-cloud-operator                                                                   
                but was required as: github.com/kiegroup/kogito-operator   
```

**Comment by sutaakar** [comment]
@Kevin-Mok Please update to the latest "snapshot" version.
To get the version run `go get github.com/kiegroup/kogito-operator@master`

**Comment by Kevin-Mok** [comment]
It seems that the tests are failing now due to `no kind is registered for the type v1beta1.KogitoBuild in scheme &#34;pkg/runtime/scheme.go` as well as timing out on some `GET` requests.

**Comment by sutaakar** [comment]
@Kevin-Mok I will take a look, there are changes which need to be ported from Kogito operator.
Will prepare a PR.

**Comment by sutaakar** [comment]
It seems to be largely addressed in https://github.com/kiegroup/rhpam-kogito-operator/pull/13 , will check what is the status with @radtriste

**Review by ricardozanini — APPROVED** [review]

**Comment by radtriste** [comment]
@Kevin-Mok PR merged. can you rebase ?

**Pull request merged**
