### PR TITLE
[1.11.x] bump bundle version to 7.12.0-4

### PR DESCRIPTION
**Pull request by davidesalerno**
Signed-off-by: Davide Salerno <dsalerno@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by radtriste — COMMENTED** [review]
Please make similar changes to https://github.com/kiegroup/rhpam-kogito-operator/pull/108/files

**Comment by davidesalerno** [comment]
> Please make similar changes to https://github.com/kiegroup/rhpam-kogito-operator/pull/108/files

Thanks @radtriste now it should be fine.

The bump-version command:

`sh hack/bump-version.sh 7.12.0 -r 7.12.0-3 -b 4`

is creating also a bundle/manifests/rhpam-kogito-operator-controller-manager_v1_serviceaccount.yaml that I didn't add. Is it right?

**Review by radtriste — APPROVED** [review]

**Comment by radtriste** [comment]
> > Please make similar changes to https://github.com/kiegroup/rhpam-kogito-operator/pull/108/files
> 
> Thanks @radtriste now it should be fine.
> 
> The bump-version command:
> 
> `sh hack/bump-version.sh 7.12.0 -r 7.12.0-3 -b 4`
> 
> is creating also a bundle/manifests/rhpam-kogito-operator-controller-manager_v1_serviceaccount.yaml that I didn't add. Is it right?

It was removed as part of https://github.com/kiegroup/rhpam-kogito-operator/commit/13eb92a6dddd3813405df73d4b50f7b570b1b653

**Review by vaibhavjainwiz — APPROVED** [review]

**Pull request merged**
