### PR TITLE
[KOGITO-5865][KOGITO-5888] BDD: Cleanup installed operators and remove namespace option

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-5865
https://issues.redhat.com/browse/KOGITO-5888

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
waiting for https://github.com/kiegroup/rhpam-kogito-operator/pull/78 first

**Review by sutaakar — APPROVED** [review]

**Comment by radtriste** [comment]
@sutaakar I merged both https://github.com/kiegroup/rhpam-kogito-operator/pull/79 and this one so that testing is ok.
Can you have a final review ?

**Comment by sutaakar** [comment]
@radtriste Looks good to me

**Pull request merged**
