### PR TITLE
[1.5.x] [RHPAM-3681] Add metering labels for Kogito pods

### PR DESCRIPTION
**Pull request by Kevin-Mok**
See: https://issues.redhat.com/browse/RHPAM-3681

Cherry-pick of #48.

## Requirements
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-cloud-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: 
- [x] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [x] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Can someone please take a look into this error?

```
fatal: [localhost]: FAILED! => changed=false 
  msg: Operator 'rhpam-kogito-operator with version 7.11.0' has different version name defined in '/tmp/community-operators-for-catalog/community-operators/rhpam-kogito-operator/7.11.0/manifests/rhpam-kogito-operator.clusterserviceversion.yaml' as 'spec.version' !!!
```

**Comment by sutaakar** [comment]
It looks like the OLM expects bundle version to be same as operator image version [1].
The difference happen due to additional build of bundle image.
It could be fixed in the next release.

[1] https://github.com/operator-framework/operator-test-playbooks/blob/master/upstream/roles/build_operator_version_bundle/tasks/main.yml#L49-L53

**Comment by spolti** [comment]
@sutaakar how it can be fixed?

**Review by vaibhavjainwiz — APPROVED** [review]

**Comment by Kevin-Mok** [comment]
I modified the PR to use @vaibhavjainwiz's [BuildContext PR](https://github.com/kiegroup/kogito-operator/pull/921) so that the metering labels are added to the `Build` resources. However, they are not added to the final build pods nor the KogitoBuild resource. I know the labels not being added to the build pods is a limitation we're facing, but I'm not sure if the KogitoBuild is supposed to have the labels or not. I tested my PR with the YAML from [this comment](https://github.com/kiegroup/rhpam-kogito-operator/pull/48#issuecomment-871370231).

**Comment by ricardozanini** [comment]
> I modified the PR to use @vaibhavjainwiz's [`BuildContext` PR](https://github.com/kiegroup/kogito-operator/pull/921) so that the metering labels are added to the `Build` and `BuildConfig` resources. However, they are not added to the final build pods nor the `KogitoBuild` resource; the labels not being added to the build pods is a limitation we're facing, and `KogitoBuild` is not supposed to have the labels.

So you're saying that PR did not solve the issue?

**Comment by spolti** [comment]
@ricardozanini not really, just had a quick conversation now with @Kevin-Mok and @vaibhavjainwiz, it is working as expected.

**Review by spolti — APPROVED** [review]

**Pull request merged**
