### PR TITLE
[KOGITO-4946] Registering correct k8s objects

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-4946

Depends on: https://github.com/kiegroup/kogito-operator/pull/845

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by spolti — APPROVED** [review]

**Review by ricardozanini — COMMENTED** [review]
Just curious about the `StartupProbe` type being in this PR. :thinking: 
Rebase problem with Kevin's PR maybe?

**Comment by radtriste** [comment]
Kevin's PR not merged yet: https://github.com/kiegroup/rhpam-kogito-operator/pull/12

**Review by ricardozanini — APPROVED** [review]

**Comment by radtriste** [comment]
> Just curious about the `StartupProbe` type being in this PR. 
> Rebase problem with Kevin's PR maybe?

Rebased with Kevin's PR

**Review by sutaakar — APPROVED** [review]

**Pull request merged**
