### PR TITLE
[KOGITO-4797] - Disable Dev mode in logging by default

### PR DESCRIPTION
**Pull request by Kaitou786**
See: https://issues.redhat.com/browse/KOGITO-4797

Signed-off-by: Tarun Khandelwal <tarkhand@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by spolti** [comment]
@Kaitou786 it is something easy to add the bot in this repo?
@msmagnanijr ^

**Review by spolti — APPROVED** [review]

**Comment by Kaitou786** [comment]
> @Kaitou786 it is something easy to add the bot in this repo?
> @msmagnanijr ^

Yeah, it is fairly easy @msmagnanijr want to do the honours?

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
Ideally, the function setup should be defined upstream and imported here. We can tackle this in the next sprint since we are about to cut the branch. Do you mind opening a JIRA to follow this up?

**Comment by Kaitou786** [comment]
> Ideally, the function setup should be defined upstream and imported here. We can tackle this in the next sprint since we are about to cut the branch. Do you mind opening a JIRA to follow this up?

Oh yeah, you are right this should be done for other function present in our main.go as well like `getWatchNamespace() ` I'll create a follow-up JIRA to keep single copy of these functions and import in this product :)

**Comment by Kaitou786** [comment]
The JIRA to keep track of it: https://issues.redhat.com/browse/KOGITO-4802

**Review by sutaakar — APPROVED** [review]

**Comment by Kaitou786** [comment]
@ricardozanini can be merged or?

**Comment by ricardozanini** [comment]
Sorry, I was waiting for the CI to pass.

**Pull request merged**
