### PR TITLE
RHPAM-3777 Allow to update prod version

### PR DESCRIPTION
**Pull request by radtriste**
Inspired by this PR: https://github.com/kiegroup/rhpam-kogito-operator/pull/52

**Example generated PR: https://github.com/radtriste/rhpam-kogito-operator/pull/2**

For LTS branch, job will be available under `/KIE/kogito/tools/{branch}/rhpam-kogito-operator-update-prod-version` and will require those parameters:
- `PROD_PROJECT_VERSION` this is the targeted product version
- `PROD_BUNDLE_SUFFIX` bundle number which will be added to the name. Default (if empty) is value `1`.
- `PROD_REPLACES_VERSION` which version do we want to replace ? Even if it seems the `replaces` field is not generated anymore... not sure why ...

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
@spolti same question here. Do we need the JIRA as well ?

**Review by vaibhavjainwiz — APPROVED** [review]

**Comment by spolti** [comment]
@radtriste no required but, at least a KIECLOUD one would be good

**Review by ricardozanini — APPROVED** [review]
Really nice man!

**Comment by radtriste** [comment]
> @radtriste no required but, at least a KIECLOUD one would be good

https://github.com/kiegroup/kogito-images/pull/579#issuecomment-890822194

**Review by sutaakar — APPROVED** [review]

**Comment by radtriste** [comment]
Added jira number param: https://github.com/radtriste/rhpam-kogito-operator/pull/3

**Review by spolti — APPROVED** [review]

**Comment by radtriste** [comment]
cannot recreate locally the bats test problem ...

**Comment by radtriste** [comment]
can someone try on his local ?

**Comment by sutaakar** [comment]
@radtriste The tests pass for me locally too

**Pull request merged**
