### PR TITLE
Fix Makefile disable_clean_cluster option

### PR DESCRIPTION
**Pull request by radtriste**
Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by spolti** [comment]
Is this change needed for 7.12.x release?

**Comment by radtriste** [comment]
I noticed 2 things:
- an omission in Makefile that I want to correct here to be able to run the BDD tests safely
- the former `kogito-operator` reference is missing that commit: https://github.com/kiegroup/kogito-operator/commit/cd75e79dcacf55777751f8db9148c21079e2e2ed which could be quite important ...
I understand it is risky ... we could leave it like that or include this in CR2, as you wish

**Comment by spolti** [comment]
As we are going to have CR2, it should be fine to merge.
thanks.

**Review by sutaakar — APPROVED** [review]

**Comment by radtriste** [comment]
ok, I see from https://github.com/kiegroup/rhpam-kogito-operator/pull/85 that the Lint was already failing ...

**Comment by radtriste** [comment]
@msmagnanijr looks like there is an error on Jenkins `readJSON` is not existing ??? Can you have a look ?

**Comment by radtriste** [comment]
@msmagnanijr somehow the [Pipeline Utility Steps](https://plugins.jenkins.io/pipeline-utility-steps/) plugin as missing ... I installed it

**Comment by radtriste** [comment]
Failure should be fixed by merging https://github.com/kiegroup/kogito-runtimes/pull/1731/ and dependent PRs

**Comment by radtriste** [comment]
failures not related to PR

**Comment by radtriste** [comment]
`Deploy source files in folder with CLI` is known bug and should be corrected by https://github.com/kiegroup/kogito-images/pull/920

**Pull request merged**
