### PR TITLE
[KOGITO-5446] - Isolate Kogito Operator APIs into a new Go module and…

### PR DESCRIPTION
**Pull request by vaibhavjainwiz**
… generate Kubernetes clients

Merge KOGITO-5446 changes in to RHPAM kogito operator

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by ricardozanini** [comment]
Hi @vaibhavjainwiz! Why do we need this PR in this operator?

**Comment by vaibhavjainwiz** [comment]
> Hi @vaibhavjainwiz! Why do we need this PR in this operator?

I raised this PR here to keep consistency between community and product version.

**Comment by ricardozanini** [comment]
> > Hi @vaibhavjainwiz! Why do we need this PR in this operator?
> 
> I raised this PR here to keep consistency between community and product version.

I don't think we need this unless required by users/customers. This operator ought to be deprecated soon.

**Comment by spolti** [comment]
It should be deprecated as soon as Kogito features come into the product, so, at some point it would not be necessary, I am not sure if it would be necessary now, would it?

**Comment by vaibhavjainwiz** [comment]
ok, then I will close this PR.

**Pull request closed without merging**
