### PR TITLE
Cleanup useless jenkinsfiles

### PR DESCRIPTION
**Pull request by radtriste**
As we won't have community releases for this repository.

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
should be merged after https://github.com/kiegroup/rhpam-kogito-operator/pull/3

**Comment by Kaitou786** [comment]
Should we also remove the `Jenkins Tests/ dsl-tests` github workflow or is it still needed?

**Comment by radtriste** [comment]
> Should we also remove the `Jenkins Tests/ dsl-tests` github workflow or is it still needed?

I think we can leave it. `jobs.groovy` is still kept for any future PR check to be handled in future Jenkins

**Review by sutaakar — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@radtriste I think you might need to update your local openapi-gen, since the YAML file has been changed and the Lint failed.

**Review by Kaitou786 — APPROVED** [review]

**Comment by sutaakar** [comment]
`Could not transfer artifact org.codehaus.plexus:plexus-utils:jar:3.0.21 from/to mirror-centra`


/jenkins test

**Pull request merged**
