### PR TITLE
[1.6.x][BXMSPROD-1306] Update to  include micro in the version.

### PR DESCRIPTION
**Pull request by AntStephenson**
See https://github.com/kiegroup/rhpam-kogito-operator/pull/30

### CODE REVIEW

**Comment by spolti** [comment]
Isn't something missing on this PR?
other have +8-8 changes and here +6-6.

**Comment by radtriste** [comment]
I guess 1.6.x is not useful ...

**Comment by AntStephenson** [comment]
@spolti @radtriste If this 1.6.x PR is not useful it can be closed. There is less changes here as it appears the extra prod YAML doesn't exist on this branch. 

If this branch isn't stale let me know and I can raise a separate PR for adding image-prod.yaml once this is merged with the correct version inside.

**Comment by radtriste** [comment]
we don't plan to productize this branch. This has been created in an automated process but is useless IMO

**Comment by AntStephenson** [comment]
OK, in that case closing this PR

**Pull request closed without merging**
