### PR TITLE
[1.11.x] BDD: Added tags to prometheus/grafana tests

### PR DESCRIPTION
**Pull request by radtriste**
to include changes from https://github.com/kiegroup/kogito-operator/pull/1122

and Correct content_sets yaml file config

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [ ] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [ ] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [ ] Pull Request contains a link to the JIRA issue
- [ ] Pull Request contains a description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [ ] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Review by sutaakar — APPROVED** [review]

**Comment by radtriste** [comment]
@msmagnanijr can you have a look ? looks like we cannot use the ODCS in PR check ?

**Comment by radtriste** [comment]
@AntStephenson FYI this PR needs to be merged to be able to rebuild the operator/bundle images correctly as a bug was introduced by https://github.com/kiegroup/rhpam-kogito-operator/pull/96 :(

**Comment by msmagnanijr** [comment]
> @msmagnanijr can you have a look ? looks like we cannot use the ODCS in PR check ?

Hey @radtriste  it is not possible as this depends on a valid Kerberos ticket and consequently being inside the Red Hat VPN.

**Comment by radtriste** [comment]
so we would need to move that RHPAM job to internal Jenkins... let's have a chat tomorrow on that.
in the meantime @spolti could we merge this ?

**Comment by msmagnanijr** [comment]
> so we would need to move that RHPAM job to internal Jenkins... let's have a chat tomorrow on that. in the meantime @spolti could we merge this ?

Sure! We can use that Jenkins CSB but let's discuss it tomorrow :)

**Comment by spolti** [comment]
will merge this one since there isn't much we can do to fix the CI problem quickly.

**Pull request merged**
