### PR TITLE
Error: Value rhpam-kogito-operator-controller-manager: invalid servic…

### PR DESCRIPTION
**Pull request by spolti**
…e account found in bundle

Signed-off-by: spolti <fspolti@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [] You've tested the new feature/bug fix in an actual OpenShift cluster
- [] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
somehow the lint is failing ... also in https://github.com/kiegroup/rhpam-kogito-operator/pull/86... not sure why

**Review by radtriste — APPROVED** [review]

**Review by sutaakar — APPROVED** [review]

**Comment by vaibhavjainwiz** [comment]
@spolti `manager.yaml` is just a template file. `rhpam-kogito-operator` prefix automatically appended to `serviceAccountName` when bundle created. I believe this change is not required.

**Comment by vaibhavjainwiz** [comment]
Error logs suggest below error :
```
time="2021-11-15T13:03:37Z" level=error msg="Error: Value rhpam-kogito-operator-controller-manager: invalid service account found in bundle. sa name cannot match service account defined for deployment spec in CSV"
```
Above issue occurs because of wrong operator-sdk version. They are using `operator-sdk version: v1.13.1` where as `rhpam-kogito-operator v1.12` is compatible with `operator-sdk-v1.2.0`

**Review by ricardozanini — APPROVED** [review]

**Comment by AntStephenson** [comment]
@vaibhavjainwiz @spolti Hi! I got a response from CVP about the error:

> OLM manages the lifecycle of the serviceaccount which is specified in the CSV.
If it's added again as a separate manifest it may interfere and cause issues with OLM’s management process (like causing upgrade failures etc).
That's the reason it need not be added by the user separately.
The suggested action is to remove the service account config yaml file from the operator’s manifest folder.

**Pull request merged**
