### PR TITLE
[KOGITO-4469] - Conditions should reflect latest evaluated status

### PR DESCRIPTION
**Pull request by sutaakar**
Signed-off-by: Karel Suta <ksuta@redhat.com>

https://issues.redhat.com/browse/KOGITO-4469

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/master/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [ ] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by sutaakar** [comment]
Porting changes from https://github.com/kiegroup/kogito-operator/pull/790 into product operator.

**Comment by sutaakar** [comment]
Latest version is not available yet in https://pkg.go.dev/github.com/kiegroup/kogito-operator , not sure how it can be published (apart from releasing proper release).
@vaibhavjainwiz @ricardozanini What approach we should take to allow picking latest Kogito operator changes in here? To be able to adjust implementation based on changes in Kogito operator.

**Comment by vaibhavjainwiz** [comment]
> Latest version is not available yet in https://pkg.go.dev/github.com/kiegroup/kogito-operator , not sure how it can be published (apart from releasing proper release).
> @vaibhavjainwiz @ricardozanini What approach we should take to allow picking latest Kogito operator changes in here? To be able to adjust implementation based on changes in Kogito operator.

To refer to master branch of `kogito-operator` inside `rhpam-kogito-operator`, you could call `go get github.com/kiegroup/kogito-operator@master`.
It will import latest commit on master

**Review by vaibhavjainwiz — APPROVED** [review]
LGTM

**Comment by ricardozanini** [comment]
That's fine for now, but I'd rather have these structures imported from upstream instead. Is it possible? Sorry for the silly question. I have to try the new codebase by myself. We should avoid this kind of task since it's hard to maintain.

**Pull request merged**
