### PR TITLE
[KOGITO-5686] RHPAM BDD tests with events against AMQ streams

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-5686

Use Red Hat AMQ streams instead of Kafka

Depends on https://github.com/kiegroup/kogito-operator/pull/971

Many thanks for submitting your Pull Request :heart:! 

Please make sure your PR meets the following requirements:

- [x] You have read the [contributors' guide](https://github.com/kiegroup/kogito-operator/blob/main/README.md#contributing-to-the-kogito-operator)
- [x] Pull Request title is properly formatted: `[KOGITO-XYZ] Subject`
- [x] Pull Request contains a link to the JIRA issue
- [x] Pull Request contains a description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Your feature/bug fix has a unit test that verifies it
- [x] You've tested the new feature/bug fix in an actual OpenShift cluster
- [ ] You've added a [RELEASE_NOTES.md](RELEASE_NOTES.md) entry regarding this change

### CODE REVIEW

**Comment by radtriste** [comment]
Should be merged after https://github.com/kiegroup/rhpam-kogito-operator/pull/63

**Comment by sutaakar** [comment]
Looks good to me.
Just please adjust the PR based on formatting requirements :)

**Comment by radtriste** [comment]
@sutaakar PR adjusted

**Review by sutaakar — APPROVED** [review]

**Comment by radtriste** [comment]
BDD tests => grafana failure

**Pull request merged**
